#!/bin/sh

# Download the firstboot script
/usr/bin/curl -o /root/firstboot https://raw.githubusercontent.com/rdobson/octoblu-vpx/master/http/debian-7/firstboot
chmod +x /root/firstboot

# create a service
cat > /etc/init.d/firstboot <<EOF
### BEGIN INIT INFO
# Provides:        firstboot
# Required-Start:  $networking
# Required-Stop:   $networking
# Default-Start:   2 3 4 5
# Default-Stop:    0 1 6
# Short-Description: Firstboot XS agent install
# Description: Install XenServer guest agents on first boot
### END INIT INFO

cd /root ; /usr/bin/nohup sh -x /root/firstboot &


EOF


# install the service
chmod +x /etc/init.d/firstboot
update-rc.d firstboot defaults

echo "finished postinstall"


